@baseUrl = http://localhost:3000/api
###VERCEL
@baseUrl = https://romandi-vadaszhaz-klinik-backend.vercel.app/api

### 1.1 Összes felhasználó lekérése ADMIN ONLY
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODljZTIxZWQ4OTgzMzBjOTQ2ZjU3YiIsImlhdCI6MTc3MDY2OTEwMCwiZXhwIjoxNzczMjYxMTAwfQ.gSPBXgN0mvKMY1JNfiPMqXXEmdkTF-VP3yVqzC97cmA
Content-Type: application/json
### 1.2 Összes orvos lekérése
GET {{baseUrl}}/users/doctors
Content-Type: application/json

### 1.3 Összes páciens lekérése ADMIN/DOCTOR ONLY
GET {{baseUrl}}/users/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OGEzZTcwNWNmNzRjNjQwYzFmNGIxYyIsImlhdCI6MTc3MDY2ODk4MCwiZXhwIjoxNzczMjYwOTgwfQ.6D_iQuX_dpyPz8QRi7XtfdkmTdf26eSWAwr4HzuWqp4
Content-Type: application/json

### 2. Regisztráció 
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name": "Doktor János",
    "email": "doktorjani@gmail.com",
    "password": "pwd",
    "phone": "+36301234567",
    "tajNumber": "666 666 789",
    "address": "9022 Győr, Admin tér 1.",
    "specialization": "Katéterezés",
    "role": "DOCTOR"
}

### 3. Bejelentkezés
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "pwd"
}
### 4. Profil lekérése
GET {{baseUrl}}/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OGEzZTcwNWNmNzRjNjQwYzFmNGIxYyIsImlhdCI6MTc3MDY2NzY0NywiZXhwIjoxNzczMjU5NjQ3fQ.Yzm4-y1NAFzJkpO77YH0cNPHe3w-LsaFJPYju9DvB3w

### 5. Profil frissítése (Név és telefonszám módosítása)
PUT {{baseUrl}}/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODljMjZmNDcyNzgyMTdlNjY3NjgyNCIsImlhdCI6MTc3MDY2Nzc3MSwiZXhwIjoxNzczMjU5NzcxfQ.14GEamK8aUT1Qcl-8971DKlMmEEKYuvh91eXatLiRpM
Content-Type: application/json

{
    "name": "Páciens János",
    "phone": "+36709998877",
    "address": "9022 Győr, Páciens tér 1."
}
### 6. Felhasználó törlése ID alapján (Admin vagy Saját maga)
DELETE {{baseUrl}}/users/6989ce21ed898330c946f57b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODljMjZmNDcyNzgyMTdlNjY3NjgyNCIsImlhdCI6MTc3MDYzOTA3OSwiZXhwIjoxNzczMjMxMDc5fQ.E_CsdK6wY2TZlDH8ezkJsbNvhPJQI8h4tL8xEo4aum4